---
title: "Mini-Project 4"
author: "Harriet Brookes-Gray, Ellen Dong, Christina Hung"
date: "April 27, 2019"
output: 
  html_document:
    df_print: paged
    code_folding: hide
---
```{r, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Opening the libraries, getting scidb data

library(tidyverse)
library(RMySQL)
library(leaflet)
library(sf)
library(dplyr)
library(ggplot2)

db <- dbConnect(MySQL(), 
                host = "scidb.smith.edu", 
                user = "mth292", 
                password = "RememberPi", 
                dbname = "citibike")
knitr::opts_chunk$set(connection = db, max.print = 20)
```


```{sql connection = db}
#SQL Query to Join the Tables

SELECT station_id, name, avg_lat, avg_lon
FROM trips 
LEFT JOIN station_months ON trips.start_station_id = station_months.station_id
WHERE start_time > "2017-01-01 06:00:00" AND stop_time < "2017-01-01 10:00:00"
GROUP BY station_id
ORDER BY start_time;
```

```{sql connection = db}
#SQL Query to Count Unique Bikes (uses bike_id key/index)

SELECT COUNT(DISTINCT bike_id) AS number_of_bikes
FROM trips 
```

```{sql connection = db}
#SQL Query to find number of users that are young

SELECT user_type, COUNT(user_type) AS number_of_users, birth_year
FROM trips 
WHERE user_type = 'subscriber'
AND birth_year > 1980
GROUP BY birth_year
ORDER BY birth_year DESC
```

```{sql connection = db}
#SQL Query to find info on oldest subscribers

SELECT user_type, gender, birth_year, COUNT(user_type) AS total_of_users_by_age, bike_id
FROM trips 
WHERE user_type = "subscriber" AND birth_year BETWEEN 1945 and 2001
GROUP BY bike_id
ORDER BY birth_year
```
  

```{r}
#Moving data on young users into R

young_users <- dbGetQuery(db, 
                    "SELECT user_type, COUNT(user_type) AS number_of_users, birth_year
FROM trips 
WHERE user_type = 'subscriber'
AND birth_year > 1980
GROUP BY birth_year
ORDER BY birth_year DESC;
")
```

```{r}
#Plotting proportion of young users

young_users_plot <- ggplot(young_users, aes(x = birth_year, y = number_of_users))
```

```{r}
#Getting info on old users into R

old_users <- dbGetQuery(db,
                     "SELECT user_type, COUNT(user_type) AS number_of_users, birth_year
                      FROM trips 
                      WHERE user_type = 'subscriber'
                      AND birth_year < 1980
                      GROUP BY birth_year
                      ORDER BY birth_year DESC;"
                          )
```


```{r}
#creating table for determining the gender of the subscribers
gender_subscribers <- dbGetQuery(db,
                     "SELECT user_type, COUNT(user_type) AS number_of_subscribers, gender
                      FROM trips 
                      WHERE user_type = 'subscriber'
                      AND birth_year BETWEEN 1945 AND 2001
                      AND start_time > '2017-01-01 06:00:00' AND stop_time < '2017-01-01 10:00:00'
                      GROUP BY gender;"
                          ) 

gender_subscribers
```



```{r}
#creating the graph of the gender of the subscribers 
cols <- c("0" = "gray", "1" = "deepskyblue2", "2" = "deeppink2")
gender_s <- ggplot(data = gender_subscribers, aes(x = gender, y = number_of_subscribers)) + 
  geom_col(aes(fill = factor(gender))) + 
  labs(title = "The Total Number of Subscribers For Each Gender", 
       x = "Gender", 
       y = "Number of Subscribers", 
       fill = "Gender") +
  scale_x_continuous(breaks = c(0, 1, 2), 
                     labels = c("Unknown/Don't Specify with Either", "Male", "Female")) +
  scale_fill_manual(values = cols, 
                     limits = c("0", "1", "2"), 
                     labels = c("Unknown/Don't Specify with Either", "Male", "Female"))

gender_s


```

#compare the number of subscribers to customers during rush hour 

```{r}
count_subscribers <- dbGetQuery(db, 
                          "SELECT birth_year, COUNT(user_type) AS total_number_of_subscribers    
                            FROM trips
                            WHERE user_type = 'subscriber'
AND birth_year >=1945
                           GROUP BY birth_year;")
count_subscribers
```

```{r}
count_customers <- dbGetQuery(db,
                            "SELECT birth_year, COUNT(user_type) AS total_number_of_customers
                            FROM trips
                            WHERE user_type = 'customer'
AND birth_year >= 1945
                            GROUP BY birth_year;")
count_customers

```

```{r}
total_users <- count_subscribers %>% full_join(count_customers)
total_users
```


```{r warning = FALSE, message = FALSE, fig.show = "hold", out.width = "50%"}
subs_vs_cus<-ggplot(data = total_users, aes(x = birth_year, y = total_number_of_customers)) +
  geom_col() + 
  geom_smooth(aes(color = "plum4")) + 
  scale_color_manual(values = c("darkviolet")) + 
  labs(title = "The Total Number of Customers In Each Birth Year Overall", 
       x = "Birth Year", 
       y = "Number of Customers") + 
  theme(legend.position = "none") + 
  scale_y_continuous(breaks= c("0+e00", "2e+05", "4e+05", "6e+05"), 
                   labels = c("0", "200000", "400000", "600000"))

subs_vs_cus2 <-ggplot(data = total_users, aes(x = birth_year, y = total_number_of_subscribers)) +
  geom_col() + 
  geom_smooth(aes(color = "plum4")) + 
  scale_color_manual(values = c("darkviolet")) + 
  labs(title = "The Total Number of Subscribers In Each Birth Year Overall", 
       x = "Birth Year", 
       y = "Number of Subscribers") + 
  theme(legend.position = "none")

# left image
subs_vs_cus
# right image
subs_vs_cus2
```



```{r}
# figuring out top 5 stations by most subscribers (using indexes)

most_subscribers <- dbGetQuery(db,
                            "SELECT birth_year, COUNT(user_type) AS total_number_of_subscribers, start_station_id, station_months.name, start_time, trips.stop_time, station_id, avg_lat, avg_lon
                            FROM trips
                            LEFT JOIN station_months ON trips.start_station_id = station_months.station_id
                            WHERE user_type = 'subscriber'
                            AND start_time > '2017-01-01 06:00:00' AND stop_time < '2017-01-01 10:00:00'
                            AND birth_year >= 1945
                            GROUP BY birth_year
                            ORDER BY total_number_of_subscribers DESC
                            LIMIT 5;")
most_subscribers
```

```{r}
#Getting top 5 stations by most subscribers into R (using indexes)

most_subscribers_gg <- dbGetQuery(db,
                            "SELECT birth_year, COUNT(user_type) AS total_number_of_subscribers, start_station_id, station_months.name, start_time, trips.stop_time, station_id, avg_lat, avg_lon
                            FROM trips
                            LEFT JOIN station_months ON trips.start_station_id = station_months.station_id
                            WHERE user_type = 'subscriber'
                            AND start_time > '2017-01-01 06:00:00' AND stop_time < '2017-01-01 10:00:00'
                            AND birth_year >= 1945
                            GROUP BY birth_year
                            ORDER BY total_number_of_subscribers DESC;")
most_subscribers_gg
```


**Map of Top 5 Bike Stations with Most Subscriber Users**
```{r}
#Making leaflet of top 5 stations by subscribers

most_subscribers_plot <- leaflet() %>%
  addTiles() %>%
  addMarkers(data = most_subscribers, lng = ~avg_lon, lat = ~avg_lat, popup = ~name)

most_subscribers_plot
```

```{r}
#Plotting number of subscribers per birth year

most_subscribers_ggplot <- ggplot(most_subscribers_gg, aes(x = birth_year, y = total_number_of_subscribers)) +
  geom_col() +
  geom_smooth(aes(color = "red")) + 
  labs(title = "How Many Subscribers Are In Each Birth Year?",
       x = "Birth Year",
       y = "Total Number of Subscribers") +
  theme(legend.position = "none")


most_subscribers_ggplot
```
